seeder:
  file: ./seeder/seeder.rb
  disabled: false

parsers:
  - page_type: locations
    file: ./parsers/locations.rb
    disabled: true
  - page_type: stores
    file: ./parsers/stores.rb
    disabled: true
  - page_type: categories
    file: ./parsers/categories.rb
    disabled: true
  - page_type: listings
    file: ./parsers/listings.rb
    disabled: true

finisher:
  file: ./finisher/finisher.rb
  disabled: false

exporters:
  - file: ./exporters/products_json.yaml
    disabled: false
  - file: ./exporters/products_csv.yaml
    disabled: false
  - file: ./exporters/product_list_csv.yaml
    disabled: false