env_vars:
 - name: needs_reparse
input_vars:
 - name: needs_reparse

seeder:
  file: ./seeder/seeder.rb
  disabled: false

parsers:
  # - page_type: store
  #   file: ./parsers/store.rb
  #   disabled: false
  # - page_type: categories
  #   file: ./parsers/categories.rb
  #   disabled: false
  # - page_type: listings
  #   file: ./parsers/listings.rb
  #   disabled: false
  # - page_type: product
  #   file: ./parsers/product.rb
  #   disabled: false
  - page_type: detail
    file: ./parsers/detail.rb
    disabled: false

finisher:
  file: ./finisher/finisher.rb
  disabled: true

exporters:
  - file: ./exporters/products_json.yaml
    disabled: false
  - file: ./exporters/products_csv.yaml
    disabled: false
  # - file: ./exporters/first_listings_page_info_csv.yaml
  #   disabled: false
